### ISSUE TITLE
Add sorting filters to booking history

### ISSUE THREAD

**Issue by mnb27** [CS305-software-Engineering/App-for-campus-facility-booking#22]

**Comment by deefreak** [comment]
closed via [https://github.com/CS305-software-Engineering/App-for-campus-facility-booking/commit/68b0cadd13fa2be08a531c9e79016cc6d4d51f17](url)

**Comment by deefreak** [comment]
closed via [](https://github.com/CS305-software-Engineering/App-for-campus-facility-booking/commit/68b0cadd13fa2be08a531c9e79016cc6d4d51f17)

**Comment by deefreak** [comment]
closed via [https://github.com/CS305-software-Engineering/App-for-campus-facility-booking/commit/68b0cadd13fa2be08a531c9e79016cc6d4d51f17](url)
